# Assignment #4 - Data Gathering and Warehousing - DSSA-5102

Instructor: Melissa Laurino</br>
Spring 2025</br>

Name: Tara Jacobsen
</br>
Date: 15 Feb 2025
<br>
<br>
<b>Only Murders in the...Database?</b><br>
An introduction to navigating databases using SQL, Python and Jupyter Notebook. <br>
<br>
A crime has taken place and you are the perfect amateur detective to solve it! 
<br>
The detective gave you the crime scene report, but you somehow lost it...? You vaguely remember that the crime
was a murder that occurred sometime on <b>Jan.15, 2018</b> and that it took place in <b>SQL
City</b>. All the clues to this mystery are buried in a huge database, and you need to use
SQL to navigate through this network of information. Your first step to solving the mystery is to retrieve the corresponding crime scene report from the police department’s database. Take a look at the cheatsheet to learn how to do this! From there, you can use your SQL skills to find the murderer.<br>

Your task for <b>Assignment #4</b> is to:<br>
- Connect to the database stored locally using Python.
- Explore the database by listing all tables, fields within the tables, and data types.
- Find out who the murderer is!<br>
- Add detailed comments to explain EVERY query or SQL command you use while we are still learning and practicing. I have my steps outlined, but please add more cells inbetween for additional queries! There is no limit on the number of queries you can use. <br>
- For each query include comments such as "SELECT all records FROM table WHERE column name = X"<br>
- Answer any prompts in markdown cells.<br>
<br>

This fabulous database was created by @NUKnightLab on Github and can be found here: https://github.com/NUKnightLab/sql-mysteries

Database files are indicated by the .db file extension. For this exercise, our database has already been created. To avoid setting your working directory, have the .db file and Assignment#4_LastName.ipynb in the same file location. There are multiple libraries that can be used to navigate database files and connect to SQL for databases that are stored on a server or your computer as a local host.

In [6]:
# Load necessary packages:
from sqlalchemy import create_engine, inspect, text # Database navigation
import sqlite3 # A second option for working with databases
import pandas as pd # Python data manilpulation

Database files are indicated by the .db file extension. For this exercise, our database has already been created. To avoid setting your working directory, have the .db file and Assignment#4_LastName.ipynb in the same file location. There are multiple libraries depending on your platform that can be used to navigate database files and connect to SQL for databases that are stored on a server or your computer as a local host.

In [7]:
# How to connect to our .db file using library SQLAlchemy
# Notice that we are not specifiying a host, password, or server since this .db file is stored locally.
db_path = "sql-murder-mystery.db"  # Change this to your actual file name
engine = create_engine(f"sqlite:///{db_path}") # Use the create_engine function to connect to the database
engine # The f is the connection string, so if we print it we can see below

Engine(sqlite:///sql-murder-mystery.db)

SQLAlchemy needs to know what kind of database we are accessing. .db files can be treated as a SQLite database. Other options include databases formatted for MySQL, PostgreSQL, etc. Database type prefixes must be included.

In [14]:
# Explore the database
# List the tables in our database:
inspector = inspect(engine)
tables = inspector.get_table_names()
tables
# So much data! How would we possibly make sense of ANY of this without SQL? :)

['crime_scene_report',
 'drivers_license',
 'facebook_event_checkin',
 'get_fit_now_check_in',
 'get_fit_now_member',
 'income',
 'interview',
 'person',
 'solution']

In [39]:
# What are the column names for each table? What table will help us get to the next clue?
print(f"Columns in '{tables[0]}':") # Print some nice text as the output so I can keep each table straight
for column in inspector.get_columns(tables[0]): # for each column in the columns in table 1
    print(column['name']) # print only the names
print() # line in between each output

print(f"Columns in '{tables[1]}':") # Print some nice text as the output so I can keep each table straight
for column in inspector.get_columns(tables[1]): # for each column in the columns in table 2
    print(column['name']) # print only the names
print() # line in between each output
  
print(f"Columns in '{tables[2]}':") # Print some nice text as the output so I can keep each table straight
for column in inspector.get_columns(tables[2]): # for each column in the columns in table 3
    print(column['name']) # print only the names
print() # line in between each output

print(f"Columns in '{tables[3]}':") # Print some nice text as the output so I can keep each table straight
for column in inspector.get_columns(tables[3]): # for each column in the columns in table 4
    print(column['name']) # print only the names
print() # line in between each output

print(f"Columns in '{tables[4]}':") # Print some nice text as the output so I can keep each table straight
for column in inspector.get_columns(tables[4]): # for each column in the columns in table 5
    print(column['name']) # print only the names
print() # line in between each output

print(f"Columns in '{tables[5]}':") # Print some nice text as the output so I can keep each table straight
for column in inspector.get_columns(tables[5]): # for each column in the columns in table 6
    print(column['name']) # print only the names
print() # line in between each output

print(f"Columns in '{tables[6]}':") # Print some nice text as the output so I can keep each table straight
for column in inspector.get_columns(tables[6]): # for each column in the columns in table 7
    print(column['name']) # print only the names
print() # line in between each output

print(f"Columns in '{tables[7]}':") # Print some nice text as the output so I can keep each table straight
for column in inspector.get_columns(tables[7]): # for each column in the columns in table 8
    print(column['name']) # print only the names
print() # line in between each output

print(f"Columns in '{tables[8]}':") # Print some nice text as the output so I can keep each table straight
for column in inspector.get_columns(tables[8]): # for each column in the columns in table 9
    print(column['name']) # print only the names

Columns in 'crime_scene_report':
date
type
description
city

Columns in 'drivers_license':
id
age
height
eye_color
hair_color
gender
plate_number
car_make
car_model

Columns in 'facebook_event_checkin':
person_id
event_id
event_name
date

Columns in 'get_fit_now_check_in':
membership_id
check_in_date
check_in_time
check_out_time

Columns in 'get_fit_now_member':
id
person_id
name
membership_start_date
membership_status

Columns in 'income':
ssn
annual_income

Columns in 'interview':
person_id
transcript

Columns in 'person':
id
name
license_id
address_number
address_street_name
ssn

Columns in 'solution':
user
value


Practice using commmands useful in queries:

In [40]:
# Example: 
# Select all records from the table crime_scene_report where type is murder:

with engine.connect() as connection:  # Establish a connection
    query = text("""SELECT * 
                    FROM crime_scene_report 
                    WHERE type='murder'
                    """)                      # Define the query - text() ensures that the query string is read as a SQL expression 
    practice = pd.read_sql(query, connection) #Use pandas to read the sql query with the connection to the database
    
# Print the results
practice

In [41]:
#Select all records from the table drivers_license where the eye color is blue:

with engine.connect() as connection: # Establish connection
# Select all records from drivers license where eye color is blue
    query = text(""" SELECT *  
                     FROM drivers_license
                     WHERE eye_color = 'blue'
                     """) 
    practice2 = pd.read_sql(query, connection) # Use pd to read query with connection to db



practice2 # Print results

id  age  height eye_color hair_color  gender plate_number  \
0     101255   18      79      blue       grey  female       5162Z1   
1     101494   48      55      blue        red  female       81X1N7   
2     101611   40      65      blue      white  female       5O8VW7   
3     101726   78      81      blue       blue  female       236T17   
4     101836   56      51      blue       grey  female       3VSG76   
...      ...  ...     ...       ...        ...     ...          ...   
2020  996697   68      73      blue      black  female       QVEW13   
2021  997724   65      73      blue     blonde    male       640570   
2022  997950   84      69      blue       grey  female       66DP8D   
2023  998114   46      50      blue      brown  female       I0GI33   
2024  998681   65      67      blue      green  female       7N21H3   

           car_make       car_model  
0             Lexus              GS  
1               Kia        Sportage  
2               GMC   Sierra Denali  
3        Oldsmobile        Intrigue  
4           Hyundai           Azera  
...             ...             ...  
2020        Ferrari  612 Scaglietti  
2021         Toyota      Highlander  
2022       Infiniti             G37  
2023  Mercedes-Benz       SLK-Class  
2024       Chrysler           Aspen  

[2025 rows x 9 columns]

In [44]:
#Select distinct records of eye_color from the table drivers_license:

with engine.connect() as connection: # Establish connection
# Select distinct eye color from driverse license
    query = text(""" SELECT DISTINCT eye_color
                     FROM drivers_license
                     """)
    practice3 = pd.read_sql(query, connection) # Use pd to read query with connection to db



practice3 # Print results

eye_color
0     brown
1     green
2     amber
3      blue
4     black

In [45]:
#Select distinct records of name from the table person:

with engine.connect() as connection: # Establish connection
# Select distinct names from person
    query = text(""" SELECT DISTINCT name
                     FROM person
                     """)
    practice4 = pd.read_sql(query, connection) # Use pd to read query with connection to db


practice4 # Print results

name
0       Christoper Peteuil
1      Kourtney Calderwood
2                Muoi Cary
3              Era Moselle
4             Trena Hornby
...                    ...
10006          Luba Benser
10007      Roxana Mckimley
10008      Cherie Zeimantz
10009          Allen Cruse
10010         Vance Hunten

[10011 rows x 1 columns]

In [137]:
#Select distinct records of gender AND car_model from the table drivers_license:

with engine.connect() as connection: # Establish connection
# Select distinct records of gender and car model from drivers license
    query = text(""" SELECT DISTINCT gender, car_model
                     FROM drivers_license
                     """)
    practice5 = pd.read_sql(query, connection) # Use pd to read query with connection to db


practice5 # Print results

gender car_model
0       male       MDX
1     female       SRX
2     female        xB
3     female     Rogue
4     female        GS
...      ...       ...
1365  female       550
1366  female   Prius c
1367  female       BRZ
1368    male   Mark LT
1369  female     HED-5

[1370 rows x 2 columns]

In [48]:
#Select distinct records of type and city from the table crime_scene_report:


with engine.connect() as connection: # Establish connection
# Select distinct records of type and city in crime scene report
    query = text(""" SELECT DISTINCT type, city
                     FROM crime_scene_report
                     """)
    practice6 = pd.read_sql(query, connection) # Use pd to read query with connection to db



practice6 # Print results

type          city
0     robbery           NYC
1      murder        Albany
2      murder          Reno
3      murder      SQL City
4       theft       Chicago
...       ...           ...
1038  robbery       Trenton
1039  bribery  Garden Grove
1040    fraud         Houma
1041  assault       Fontana
1042  assault       Trenton

[1043 rows x 2 columns]

In [136]:
#Select all records from table drivers_license where the age is == 40:

with engine.connect() as connection: # Establish connection
# Select all records from drivers license where age is 40
    query = text(""" SELECT *
                     FROM drivers_license
                     WHERE age = 40
                     """)
    practice7 = pd.read_sql(query, connection) # Use pd to read query with connection to db


practice7 # Print results

id  age  height eye_color hair_color  gender plate_number  \
0    101611   40      65      blue      white  female       5O8VW7   
1    103725   40      57     black      green  female       81WZ22   
2    116863   40      63     black      black  female       1ZSI8C   
3    118332   40      75     green      black    male       6SG3W0   
4    122134   40      61     black      white  female       8616Y4   
..      ...  ...     ...       ...        ...     ...          ...   
143  969815   40      63     green      black  female       G40MZY   
144  973824   40      50     brown       blue  female       LEJ771   
145  974364   40      52     green      black  female       822S0D   
146  990554   40      63     amber      white    male       XH2QC0   
147  992954   40      53     black     blonde  female       1QX3S8   

       car_make       car_model  
0           GMC   Sierra Denali  
1    Land Rover      Freelander  
2          Audi              A8  
3    Mitsubishi        Diamante  
4     Chevrolet           Astro  
..          ...             ...  
143   Chevrolet   Suburban 2500  
144        Ford            F250  
145        Ford            E250  
146    Chrysler  Town & Country  
147       Lexus              IS  

[148 rows x 9 columns]

In [50]:
#Select all records from table drivers_license where the age is greater than 21:


with engine.connect() as connection: # Establish connection
# Select all records from driverse_license where age is > 21
    query = text(""" SELECT *
                     FROM drivers_license
                     WHERE age > 21
                     """)
    practice8 = pd.read_sql(query, connection) # Use pd to read query with connection to db



practice8 # Print results

id  age  height eye_color hair_color  gender plate_number  \
0     100280   72      57     brown        red    male       P24L4U   
1     100460   63      72     brown      brown  female       XF02T6   
2     101029   62      74     green      green  female       VKY5KR   
3     101198   43      54     amber      brown  female       Y5NZ08   
4     101494   48      55      blue        red  female       81X1N7   
...      ...  ...     ...       ...        ...     ...          ...   
9434  999509   42      80     amber       blue  female       8E403S   
9435  999536   56      65     green      green  female       4FFUD5   
9436  999940   71      61     green      green    male       1B8QN8   
9437  999981   67      69     brown       blue  female       1684K3   
9438  999986   49      58     green       grey    male       F8F64H   

        car_make car_model  
0          Acura       MDX  
1       Cadillac       SRX  
2          Scion        xB  
3         Nissan     Rogue  
4            Kia  Sportage  
...          ...       ...  
9434      Morgan    Aero 8  
9435     Mercury     Sable  
9436  Mitsubishi   Eclipse  
9437  Land Rover       LR2  
9438       Lexus        LS  

[9439 rows x 9 columns]

In [51]:
#Select all records from table drivers_license where the age is less than OR equal to 21:
#Do you see a difference in the number of rows?

with engine.connect() as connection: # Establish connection
# Select all records from driverse license where the age is less than or equal to 21
    query = text(""" SELECT *
                     FROM drivers_license
                     WHERE age <= 21
                     """)
    practice9 = pd.read_sql(query, connection) # Use pd to read query with connection to db



practice9 # Print results

# 9438 versus 567 rows

id  age  height eye_color hair_color  gender plate_number  \
0    101255   18      79      blue       grey  female       5162Z1   
1    102536   21      76      blue     blonde    male       3DG322   
2    105064   20      53     black       blue    male       25UO1B   
3    108374   18      63     brown        red    male       X2KE6N   
4    109617   19      76     green       blue    male       UO2B77   
..      ...  ...     ...       ...        ...     ...          ...   
563  992923   20      77     black      brown  female       GT0EX0   
564  996996   20      56     black      green  female       5Y0W6U   
565  998350   20      78     amber       grey    male       6HRAXP   
566  999923   19      77     amber      black  female       5L0ZI4   
567  999993   18      63     black      black  female       6UZO2O   

          car_make     car_model  
0            Lexus            GS  
1           Suzuki  Grand Vitara  
2    Mercedes-Benz      SL-Class  
3             Ford        Escape  
4         Infiniti             G  
..             ...           ...  
563           MINI        Cooper  
564       Maserati  Quattroporte  
565     Mitsubishi        Lancer  
566            GMC   Sierra 3500  
567       Cadillac       DeVille  

[568 rows x 9 columns]

In [52]:
#Select all records from table get_fit_now_check_in and order by check_in_date:
#Do you see a difference in the number of rows?

with engine.connect() as connection: # Establish connection
# Select all rows from get fit now check in and order by date
    query = text(""" SELECT *
                     FROM get_fit_now_check_in
                     ORDER BY check_in_date
                     """)
    practice10 = pd.read_sql(query, connection) # Use pd to read query with connection to db



practice10

# 2702 rows

membership_id  check_in_date  check_in_time  check_out_time
0            82GA2       20170101            431            1116
1            KE0FH       20170101            375             447
2            C84S4       20170101            580             864
3            XTE42       20170101           1188            1199
4            TQU5U       20170101            381            1069
...            ...            ...            ...             ...
2698         C581L       20180430             76             642
2699         0U51D       20180501             88             218
2700         7788A       20180501            532             705
2701         VHN8M       20180501            658             989
2702         MORMA       20180501           1029            1183

[2703 rows x 4 columns]

In [53]:
#Select all records from table get_fit_now_check_in and order by check_in_date and order by check_in_time:
#Do you see a difference in the order of the rows?

with engine.connect() as connection: # Establish connection
# Select all records from get fit now check in and order by both check in date and time
    query = text(""" SELECT *
                     FROM get_fit_now_check_in
                     ORDER BY check_in_date, check_in_time
                     """)
    practice10 = pd.read_sql(query, connection) # Use pd to read query with connection to db

practice10 # Print results

# Rows are now ordered by both date and check in time

membership_id  check_in_date  check_in_time  check_out_time
0            C581L       20170101             23            1071
1            3JP0X       20170101            154             609
2            J2033       20170101            242             955
3            KE0FH       20170101            375             447
4            TQU5U       20170101            381            1069
...            ...            ...            ...             ...
2698         133ED       20180430           1197            1200
2699         0U51D       20180501             88             218
2700         7788A       20180501            532             705
2701         VHN8M       20180501            658             989
2702         MORMA       20180501           1029            1183

[2703 rows x 4 columns]

Now that we have practiced, let's solve this murder!

All we know at the start of our investigation is the <b>murder</b> occurred on <b>Jan.15, 2018</b> and that it took place in <b>SQL City<b>.

In [81]:
#Write a query in SQL to view the crime scene report 
#for the murder occurred on Jan.15, 2018 and that it took place in SQL City.
#Select ALL records FROM the table WHERE...

pd.set_option('display.max_colwidth', None) # No max column width so I can read all of the description

with engine.connect() as connection: # Establish connection
    # Define query to select all records from crime scene report where date is 20180115 and city is SQL City and type is murder
    query = text(""" SELECT * 
                     FROM crime_scene_report
                     WHERE date == 20180115 AND city == 'SQL City' AND type == 'murder'
                     """)
    report = pd.read_sql(query, connection) # Use pd to read query with connection to db

report # Print result





date    type  \
0  20180115  murder   

                                                                                                                                                                                 description  \
0  Security footage shows that there were 2 witnesses. The first witness lives at the last house on "Northwestern Dr". The second witness, named Annabel, lives somewhere on "Franklin Ave".   

       city  
0  SQL City

Another clue! It looks like we have two witnesses! Now who are they and how do we find them?

In [86]:
#Write two queries in SQL to find each witness in the person table. 
#For the first query as first_witness, select all the records from person where the address_street_name is Northwestern Drive and order by adress_number
#Fetch the first_witness

with engine.connect() as connection: # Establish connection
    # Define query to select all records from person where the address street name is Northwestern Dr
    # and order by address_number DESC so the last house appears first. Limit to first 5 rows.
    query = text(""" SELECT * 
                     FROM person
                     WHERE address_street_name == 'Northwestern Dr' 
                     ORDER BY address_number DESC
                     LIMIT 5
                     """)
    witness1 = pd.read_sql(query, connection) # Use pd to read query with connection to db

witness1 # Print result

# 14887, Morty Schapiro

id            name  license_id  address_number address_street_name  \
0  14887  Morty Schapiro      118009            4919     Northwestern Dr   
1  17729  Lasonya Wildey      439686            3824     Northwestern Dr   
2  53890  Sophie Tiberio      957671            3755     Northwestern Dr   
3  73368  Torie Thalmann      773862            3697     Northwestern Dr   
4  96595   Coretta Cubie      303645            3631     Northwestern Dr   

         ssn  
0  111564949  
1  917817122  
2  442830147  
3  341559436  
4  378403829

We have identified our first witness as Morty Schapiro (14887). Now lets find the second!

In [87]:
#For the third query as second_witness,
#Select all the records from person where the address_street_name is Frnaklin Ave and the name includes Annabel. 
#Fetch the second_witness

with engine.connect() as connection: # Establish connection
    # Define query to select all records from person where the address street name is Franklin Ave
    # and name includes Annabel
    query = text(""" SELECT * 
                     FROM person
                     WHERE address_street_name == 'Franklin Ave'
                     AND name LIKE '%Annabel%'
                     """)
    witness2 = pd.read_sql(query, connection) # Use pd to read query with connection to db

witness2 # Print result

# 16371, Annabel Miller

id            name  license_id  address_number address_street_name  \
0  16371  Annabel Miller      490173             103        Franklin Ave   

         ssn  
0  318771143

We have identified our second witness as Annabel Miller (16371). What were their witness statements? What did they see?

In [89]:
#For our fourth query, witness_statements, lets find out what each witness saw...or claim they saw?
#Select the peron's name and interview where the person_id is X, X (Get the ID from the above queries)

# 14887
# 16371

with engine.connect() as connection: # Establish connection
    # Define query to select all records from interview where person_id = 14887
    query = text(""" SELECT * 
                     FROM interview
                     WHERE person_id = 14887
                     """)
    interview1 = pd.read_sql(query, connection) # Use pd to read query with connection to db

interview1 # Print result


# I heard a gunshot and then saw a man run out. He had a "Get Fit Now Gym" bag.
# The membership number on the bag started with "48Z". Only gold members have
# those bags. The man got into a car with a plate that included "H42W".

person_id  \
0      14887   

                                                                                                                                                                                                                        transcript  
0  I heard a gunshot and then saw a man run out. He had a "Get Fit Now Gym" bag. The membership number on the bag started with "48Z". Only gold members have those bags. The man got into a car with a plate that included "H42W".

In [90]:
with engine.connect() as connection: # Establish connection
    # Define query to select all records from interview where person_id = 16371
    query = text(""" SELECT * 
                     FROM interview
                     WHERE person_id = 16371
                     """)
    interview2 = pd.read_sql(query, connection) # Use pd to read query with connection to db

interview2 # Print result

# I saw the murder happen, and I recognized the killer from my gym when I was
# working out last week on January the 9th.

person_id  \
0      16371   

                                                                                                              transcript  
0  I saw the murder happen, and I recognized the killer from my gym when I was working out last week on January the 9th.

A few new clues! Explore the different clues with multiple queries. Seems like a reliable statement!

In [135]:
#Create a query to select for the following clues: (You can create multiple queries or combine them into one and go from there.)
#Remember to write our your query in the comments!


with engine.connect() as connection: # Establish connection
    # Define query to select all records from get_fit_now_check_in where member ID includes 48Z and the member checked in on 1/9
    query = text(""" SELECT * 
                     FROM get_fit_now_check_in
                     WHERE membership_id LIKE '%48Z%'
                     AND check_in_date = '20180109'
                     """)
    clue1 = pd.read_sql(query, connection) # Use pd to read query with connection to db

clue1 # Print result


# Options: 48Z7A, 48Z55

membership_id  check_in_date  check_in_time  check_out_time
0         48Z7A       20180109           1600            1730
1         48Z55       20180109           1530            1700

In [134]:
with engine.connect() as connection: # Establish connection
    # Define query to select all records from get_fit_now_member with possible ID numbers
    query = text(""" SELECT * 
                     FROM get_fit_now_member
                     WHERE id IN ('48Z7A', '48Z55')
                     """)
    clue2 = pd.read_sql(query, connection) # Use pd to read query with connection to db

clue2 # Print result

# IDs: 67318, 28819
# Names: Jeremy Bowers, Joe Germuska

id  person_id           name  membership_start_date membership_status
0  48Z55      67318  Jeremy Bowers               20160101              gold
1  48Z7A      28819   Joe Germuska               20160305              gold

We have a suspect! Lets check their witness statement. Do they have an alibi?

In [133]:
pd.set_option('display.max_colwidth', None) # No max column width so I can read all of the transcript

with engine.connect() as connection: # Establish connection
    # Define query to select all records from interview with ID numbers
    query = text(""" SELECT * 
                     FROM interview
                     WHERE person_id IN ('67318', '28819')
                     """)
    clue3 = pd.read_sql(query, connection) # Use pd to read query with connection to db

clue3 # Print result


# Only one of the above ID numbers was interviewed. 
# 67318 Jeremy Bowers was hired by someone. 

person_id  \
0      67318   

                                                                                                                                                                                                                                           transcript  
0  I was hired by a woman with a lot of money. I don't know her name but I know she's around 5'5" (65") or 5'7" (67"). She has red hair and she drives a Tesla Model S. I know that she attended the SQL Symphony Concert 3 times in December 2017.\n

Uh oh...turns out it wasn't just one person behind the crime...who is this additional person involved?

In [132]:

with engine.connect() as connection: # Establish connection
    # Define query to select all records from drivers_license where height is between
    # 65 and 67 inches, red hair, and car is Tesla 
    query = text(""" SELECT * 
                     FROM drivers_license
                     WHERE height BETWEEN 65 AND 67
                     AND hair_color = 'red'
                     AND car_make = 'Tesla'
                     """)
    clue4 = pd.read_sql(query, connection) # Use pd to read query with connection to db

clue4 # Print result

# 202298, 291182, 918773

id  age  height eye_color hair_color  gender plate_number car_make  \
0  202298   68      66     green        red  female       500123    Tesla   
1  291182   65      66      blue        red  female       08CM64    Tesla   
2  918773   48      65     black        red  female       917UU3    Tesla   

  car_model  
0   Model S  
1   Model S  
2   Model S

In [131]:
with engine.connect() as connection: # Establish connection
    # Define query to select all records from person and license_id is one from above
    query = text(""" SELECT * 
                     FROM person
                     WHERE license_id IN ('202298', '291182', '918773')
                     """)
    clue5 = pd.read_sql(query, connection) # Use pd to read query with connection to db

clue5 # Print result

# 78881, 90700, 99716
# Red Korb, Regina George, Miranda Priestly

id              name  license_id  address_number address_street_name  \
0  78881          Red Korb      918773             107         Camerata Dr   
1  90700     Regina George      291182             332           Maple Ave   
2  99716  Miranda Priestly      202298            1883          Golden Ave   

         ssn  
0  961388910  
1  337169072  
2  987756388

Three different people match this description! Now which one attended the SQL Symphony Concert three times? 

In [129]:
#Let's find the killer!
#Remember to write our your query in the comments!


with engine.connect() as connection: # Establish connection
    # Define query to select all records from facebook_event_checkin where the event
    # is SQL Symphony Concert where they attended 3+ times and the date includes
    # 2017 December and the person_id is one of the above 
    query = text(""" SELECT * 
                     FROM facebook_event_checkin
                     WHERE event_name = 'SQL Symphony Concert'
                     GROUP BY person_id
                     HAVING COUNT(*) >= 3
                     AND date LIKE '%201712%'
                     AND person_id IN (78881, 90700, 99716)
                     """)
    clue5 = pd.read_sql(query, connection) # Use pd to read query with connection to db

clue5 # Print result

# Only one! 99716, Miranda Priestly

person_id  event_id            event_name      date
0      99716      1143  SQL Symphony Concert  20171206

<b>The murderer(s) is/are:</b> Jeremy Bowers (physical murderer) and Miranda Priestly (person who hired murderer)

In [138]:
#Disconnect from the database. Always remember to disconnect :) 
connection.close() # Disconnect 